get:
  tags:
    - products
  summary: get single product
  parameters:
    - name: id
      in: path
      description: ID of product
      required: true
      schema:
        type: integer
        format: int64
  responses:
    "200":
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '../schemas/Product.yaml'
put:
  tags:
    - admin
  summary: update value of a product
  security:
    BearerAuth: []
  parameters:
    - name: id
      in: path
      description: ID of product
      required: true
      schema:
        type: integer
        format: int64
  responses:
    "201":
      description: product updated
    "400":
      description: invalid input, object invalid
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            name:
              description: Updated name of product
              type: string
            description:
              description: Updated description of the product
            variant:
              description: Updated variant of the product
            size:
              description: Updated size of the product
delete:
  tags:
    - admin
  summary: Deletes a product
  security:
    BearerAuth: []
  parameters:
    - name: id
      in: path
      description: ID of product
      required: true
      schema:
        type: integer
        format: int64
  responses:
    "200": 
      description: Product deleted successfully
    "400":
      description: Invalid ID supplied
    "404":
      description: Product not found
