openapi: 3.0.1
servers:
  - description: SwaggerHub API
    url: HTTP
  - description: SwaggerHub API
    url: HTTPS
info:
  description: This is a fake Ecommerce API
  version: 1.0.0
  title: Fake Ecommerce API
  contact:
    email: hoan.ho@integrify.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admin
    description: Secured Admin-only calls
  - name: products
    description: Products operation available to regular users
  - name: users
    description: Operations about user
  - name: categories
    description: Operations related to categories
  - name: cart
    description: Operations related to cart
paths:
  /products:
    get:
      tags:
        - products
      summary: get all products
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      tags:
        - admin
      summary: create a new product
      security:
        BearerAuth: []
      responses:
        '201':
          description: product created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: product already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
            description: Product to create
  '/products/{id}':
    get:
      tags:
        - products
      summary: get single product
      parameters:
        - name: id
          in: path
          description: ID of product
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    put:
      tags:
        - admin
      summary: update value of a product
      security:
        BearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of product
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '201':
          description: product updated
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  description: Updated name of product
                  type: string
                description:
                  description: Updated description of the product
                variant:
                  description: Updated variant of the product
                size:
                  description: Updated size of the product
    delete:
      tags:
        - admin
      summary: Deletes a product
      security:
        BearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of product
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Product deleted successfully
        '400':
          description: Invalid ID supplied
        '404':
          description: Product not found
  /users:
    get:
      tags:
        - admin
      summary: Get all users
      description: Admin can get all users
      operationId: getAllUsers
      security:
        BearerAuth: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags:
        - users
      summary: Create a new user
      description: Create a new user when sign up
      operationId: createUser
      parameters:
        - in: body
          name: body
          description: New user object
          required: true
          schema:
            $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '405':
          description: Invalid input
  '/users/{id}':
    put:
      tags:
        - users
      summary: Update current user
      description: This can only be done by the logged in user
      operationId: updateUser
      parameters:
        - name: firstName
          in: path
          required: false
          type: string
        - name: lastName
          in: path
          required: false
          type: string
        - name: email
          in: path
          required: true
          type: string
        - in: body
          name: body
          description: Updated user object
          required: true
          schema:
            $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User information updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    format: int64
                    example: 1
                  firstName:
                    type: string
                    example: Alex
                  lastName:
                    type: string
                    example: Brown
                  email:
                    type: string
                    example: alex@email.com
  /categories:
    get:
      tags:
        - categories
      summary: Get all categories
      parameters:
        - name: limit
          in: query
          required: true
          type: integer
      responses:
        '200':
          description: successful operation
    post:
      tags:
        - admin
      summary: create a new category
      security:
        BearerAuth: []
      responses:
        '201':
          description: category created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: category already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
            description: Category to create
  '/categories{id}':
    get:
      tags:
        - categories
      summary: Get single category
      parameters:
        - name: id
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
  /carts:
    get:
      tags:
        - cart
      summary: get cart
      description: get individual shopping cart
      security:
        BearerAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CartItem'
        '404':
          description: content not found
    post:
      tags:
        - cart
      summary: add to cart
      description: add a new item to cart
      security:
        BearerAuth: []
      responses:
        '201':
          description: item added
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartItem'
            description: Item to add
  '/carts/{id}':
    delete:
      tags:
        - cart
      summary: Deletes an item
      description: Delete an item from cart based on quantity
      security:
        BearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID of item
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Item deleted successfully
        '400':
          description: Invalid ID supplied
        '404':
          description: Product not found
components:
  schemas:
    Product:
      Product: null
      type: object
      required:
        - id
        - name
        - description
        - category
        - variant
        - size
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: iPhone 14
        description:
          type: string
          example: Smartphone by Apple
        category:
          type: string
          example: Electronics
        variant:
          type: string
          example: red
        size:
          type: string
          example: small
    User:
      type: object
      properties:
        id:
          type: number
          format: int64
          example: 1
        firstName:
          type: string
          example: John
        lastName:
          type: string
          example: Doe
        email:
          type: string
          example: john@email.com
        role:
          type: string
          enum:
            - admin
            - user
    Category:
      type: object
      properties:
        id:
          type: number
          format: int64
          example: 1
        name:
          type: string
          example: Clothes
        image:
          type: string
          example: 'https://placeimg.com/640/480/any'
    CartItem:
      CartItem: null
      type: object
      required:
        - id
        - name
        - description
        - category
        - variant
        - size
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: iPhone 14
        description:
          type: string
          example: Smartphone by Apple
        category:
          type: string
          example: Electronics
        variant:
          type: string
          example: red
        size:
          type: string
          example: small
        quantity:
          type: integer
          format: int64
          example: 1
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://example.com/oauth/authorize'
          tokenUrl: 'https://example.com/oauth/token'
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants access to admin operations
